CREATE DATABASE IF NOT EXISTS test;
USE DATABASE test;

CREATE TABLE IF NOT EXISTS tv (
 	id INT AUTO_INCREMENT PRIMARY KEY,
 	marque VARCHAR(50),
 	modele VARCHAR(50),
 	taille INT,
 	annee SMALLINT
);